apiVersion: v1
kind: Service
metadata:
  name: dante-service
spec:
  selector:
    app: dante
  ports:
  - name: dante-port
    protocol: TCP
    port: 1080
    targetPort: 1080
    nodePort: 49374
  type: NodePort
